# Generated by Django 4.0 on 2022-09-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_content_difficulty_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
