# Generated by Django 4.0 on 2022-09-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_alter_content_author_alter_content_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='hints',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='problem_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='content',
            name='solution',
            field=models.TextField(),
        ),
    ]
